name: deploy (Deploy to IBM Cloud Canary)

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [deploy-canary]

jobs:
  deploy-canary:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Grab latest canary release
        run: yarn update-canary
      - name: Build project
        run: yarn build
      - name: Deploying to IBM Cloud (Canary)
        uses: carbon-design-system/action-ibmcloud-cf@v1.2.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-html-test
          cf-manifest: manifest-canary.yml
          deploy-dir: ./
  deploy-rtl:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Grab latest canary release
        run: yarn update-canary
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: .env
        env:
          ENABLE_RTL: true
      - name: Build project
        run: yarn build
      - name: Deploying to IBM Cloud (Canary - RTL)
        uses: carbon-design-system/action-ibmcloud-cf@v1.2.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-html-rtl
          cf-manifest: manifest-rtl.yml
          deploy-dir: ./
