name: deploy (Deploy to IBM Cloud Staging)

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [ deploy-staging ]

jobs:
  deploy-staging:
    runs-on: ubuntu-16.04
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: yarn install
      - name: Grab latest next release
        run: yarn update-next
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: .env
        env:
          DDS_CALLOUT_DATA: true
      - name: Build project
        run: yarn build
      - name: Deploying to IBM Cloud (Staging)
        uses: carbon-design-system/action-ibmcloud-cf@v1.3.0
        with:
          cloud-api-key: ${{ secrets.CLOUD_API_KEY }}
          cf-org: ibm-digital-design
          cf-space: ibmdotcom-production
          cf-region: us-south
          cf-app: ibmdotcom-web-components-html-staging
          cf-manifest: manifest-staging.yml
          deploy-dir: ./
      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
        if: failure()
