name: percy-update-base

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [deploy-canary]

concurrency:
  group: percy-update-base-${{ github.ref }}
  cancel-in-progress: true

jobs:
  percy-update:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom-web-components-test'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['18.x']
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install
      - name: Grab latest canary release
        run: yarn update-canary
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: .env
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Build the app
        run: yarn build
      - name: Run e2e tests
        run: yarn test:e2e:local
  percy-update-upstream:
    if: github.repository == 'carbon-design-system/carbon-for-ibm-dotcom-web-components-test'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [ '18.x' ]
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install
      - name: Grab latest canary release
        run: yarn update-canary
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: .env
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_UPSTREAM }}
      - name: Build the app
        run: yarn build
      - name: Run e2e tests
        run: yarn test:e2e:local
