name: percy-update-base

on:
  push:
    branches:
      - master

jobs:
  percy-update:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        node-version: ['14.x']
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn install
      - name: Grab latest canary release
        run: yarn update-canary
      - name: Set env vars
        uses: ./.github/actions/set-dotenv
        with:
          env-file: .env
        env:
          DDS_CALLOUT_DATA: true
      - name: Build the app
        run: yarn build
      - name: Run e2e tests
        run: PERCY_TOKEN=${{ secrets.PERCY_TOKEN }} yarn test:e2e:local
      - name: Run e2e tests (upstream)
        run: PERCY_TOKEN=${{ secrets.PERCY_TOKEN_UPSTREAM }} yarn test:e2e:local
